### ISSUE TITLE
install fails missing deps 

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/mysql#1]
Modular-Bikeshed-20171023

mysql/default =>  Problem: conflicting requestsn  - nothing provides libnuma.so.1()(64bit) needed by community-mysql-server-5.7.19-6.module_bd440b63.x86_64

mysql/server =>  Problem: conflicting requestsn  - nothing provides libnuma.so.1()(64bit) needed by community-mysql-server-5.7.19-6.module_bd440b63.x86_64

**Comment by alexxa** [comment]
@KarstenHopp

**Comment by nphilipp** [comment]
[Here's how to fix issues like this.](https://docs.pagure.org/modularity/development/building-modules/installation-dependency-issues.html)

**Comment by KarstenHopp** [comment]
rhbz#1513943, fixed
